builders:
  conformance_registry:
    import: "bin/conformance/builder.dart"
    builder_factories: ["conformanceRegistryBuilder"]
    build_extensions: {".dart": [".conformance.g.dart"]}
    auto_apply: root_package
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

targets:
  $default:
    builders:
      protoc_plugin:
        generate_for:
          include:
            - proto/**
      protovalidate:conformance_registry:
        enabled: true
        generate_for:
          - bin/conformance/conformance_registry.dart