name: protovalidate
description: Protocol Buffer validation for Dart - provides runtime validation of protobuf messages based on rules defined in proto files.
version: 0.1.0
repository: https://github.com/bufbuild/protovalidate-dart

environment:
  sdk: ^3.0.0

dependencies:
  protobuf:
    path: ../protobuf.dart/protobuf
  fixnum: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  build_runner: ^2.6.1
