name: protovalidate
description: Protocol Buffer validation for Dart - provides runtime validation of protobuf messages based on rules defined in proto files.
version: 0.1.0
repository: https://github.com/titanous/protovalidate-dart
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  protobuf: ^5.0.0
  fixnum: ^1.1.1
  cel:
    git:
      url: https://github.com/titanous/cel-dart
      ref: fbcc62d6fc0fafd42317a5289e5ebe857c57f812

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  build_runner: ^2.4.0
  build_test: ^3.3.2
  build: ^3.0.2
  source_gen: ^3.1.0
  glob: ^2.1.2
  analyzer: ^8.1.1
  path: ^1.9.0
  protoc_plugin: ^23.0.0

dependency_overrides:
  protobuf:
    path: ../protobuf.dart/protobuf
  cel:
    path: ../cel-dart
  protoc_plugin:
    git:
      url: https://github.com/titanous/protobuf.dart
      ref: efb8b3d70edf6619a4873fd9785e724c91720f09
      path: protoc_plugin
